valor = input('Digite algo: ')
print('O tipo primitivo de valor é',type(valor))
print('Tem espaços?',valor.isspace())
print('É numérico?',valor.isnumeric())
print('É alfabético?',valor.isalpha())
print('É alfanumérico?',valor.isalnum())
print('Está em maiúsculas?',valor.isupper())
print('Está em minúsculas',valor.islower())
print('Está capitalizada?',valor.istitle())